# GitHub Action that verifies complience with Black.
# If all Python code in the pull request is compliant with Black then this Action does nothing.
# Othewrwise, it action fails.

name: black-complient
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
